//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskInfo()
        {
            this.Implementation = 0;
        }
    
        public int TaskInfoId { get; set; }
        public string Description { get; set; }
        public System.DateTime Deadline { get; set; }
        public short Implementation { get; set; }
        public int CreatorUserId { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User CreatorUser { get; set; }
        public virtual User Developer { get; set; }
    }
}
